// ── Built-in libraries: exercises, mobility drills + routines, preset workouts ──
// Exercise: [id, name, body part, type, equipment]   type: wr weight×reps · r reps · d time · dt distance+time
const EX_ROWS = [
  // Chest
  ['bench', 'Bench Press (Barbell)', 'Chest', 'wr', 'Barbell'], ['bench-db', 'Bench Press (Dumbbell)', 'Chest', 'wr', 'Dumbbell'], ['bench-sm', 'Bench Press (Smith Machine)', 'Chest', 'wr', 'Machine'],
  ['incline-bb', 'Incline Bench Press (Barbell)', 'Chest', 'wr', 'Barbell'], ['incline-db', 'Incline Bench Press (Dumbbell)', 'Chest', 'wr', 'Dumbbell'], ['decline-bb', 'Decline Bench Press (Barbell)', 'Chest', 'wr', 'Barbell'],
  ['chest-press', 'Chest Press (Machine)', 'Chest', 'wr', 'Machine'], ['incline-press-m', 'Incline Chest Press (Machine)', 'Chest', 'wr', 'Machine'], ['fly-cable', 'Cable Fly', 'Chest', 'wr', 'Cable'],
  ['fly-low', 'Low-to-High Cable Fly', 'Chest', 'wr', 'Cable'], ['fly-db', 'Dumbbell Fly', 'Chest', 'wr', 'Dumbbell'], ['pec-deck', 'Pec Deck', 'Chest', 'wr', 'Machine'],
  ['dip', 'Chest Dip', 'Chest', 'r', 'Bodyweight'], ['dip-w', 'Chest Dip (Weighted)', 'Chest', 'wr', 'Bodyweight'], ['pushup', 'Push Up', 'Chest', 'r', 'Bodyweight'],
  ['pushup-incline', 'Incline Push Up', 'Chest', 'r', 'Bodyweight'], ['pushup-decline', 'Decline Push Up', 'Chest', 'r', 'Bodyweight'], ['pushup-band', 'Banded Push Up', 'Chest', 'r', 'Band'],
  ['svend', 'Plate Squeeze Press', 'Chest', 'wr', 'Other'],
  // Back
  ['deadlift', 'Deadlift (Barbell)', 'Back', 'wr', 'Barbell'], ['deadlift-trap', 'Trap Bar Deadlift', 'Back', 'wr', 'Barbell'], ['deadlift-sumo', 'Sumo Deadlift', 'Back', 'wr', 'Barbell'],
  ['rack-pull', 'Rack Pull', 'Back', 'wr', 'Barbell'], ['row-bb', 'Bent Over Row (Barbell)', 'Back', 'wr', 'Barbell'], ['row-pendlay', 'Pendlay Row', 'Back', 'wr', 'Barbell'],
  ['row-tbar', 'T-Bar Row', 'Back', 'wr', 'Barbell'], ['row-db', 'Dumbbell Row', 'Back', 'wr', 'Dumbbell'], ['row-chest', 'Chest Supported Row (Dumbbell)', 'Back', 'wr', 'Dumbbell'],
  ['row-cable', 'Seated Cable Row', 'Back', 'wr', 'Cable'], ['row-machine', 'Row (Machine)', 'Back', 'wr', 'Machine'], ['row-inverted', 'Inverted Row', 'Back', 'r', 'Bodyweight'],
  ['row-band', 'Band Row', 'Back', 'r', 'Band'], ['pulldown', 'Lat Pulldown (Cable)', 'Back', 'wr', 'Cable'], ['pulldown-cg', 'Close-Grip Lat Pulldown', 'Back', 'wr', 'Cable'],
  ['pulldown-sa', 'Single-Arm Lat Pulldown', 'Back', 'wr', 'Cable'], ['pullover-cable', 'Straight-Arm Pulldown', 'Back', 'wr', 'Cable'], ['pullover-db', 'Dumbbell Pullover', 'Back', 'wr', 'Dumbbell'],
  ['pullup', 'Pull Up', 'Back', 'r', 'Bodyweight'], ['pullup-w', 'Pull Up (Weighted)', 'Back', 'wr', 'Bodyweight'], ['pullup-assist', 'Assisted Pull Up (Machine)', 'Back', 'wr', 'Machine'],
  ['chinup', 'Chin Up', 'Back', 'r', 'Bodyweight'], ['chinup-w', 'Chin Up (Weighted)', 'Back', 'wr', 'Bodyweight'], ['back-ext', 'Back Extension', 'Back', 'r', 'Bodyweight'],
  ['back-ext-w', 'Back Extension (Weighted)', 'Back', 'wr', 'Other'], ['good-morning', 'Good Morning', 'Back', 'wr', 'Barbell'], ['shrug-bb', 'Shrug (Barbell)', 'Back', 'wr', 'Barbell'],
  ['shrug-db', 'Shrug (Dumbbell)', 'Back', 'wr', 'Dumbbell'], ['superman', 'Superman Hold', 'Back', 'd', 'Bodyweight'],
  // Shoulders
  ['ohp', 'Overhead Press (Barbell)', 'Shoulders', 'wr', 'Barbell'], ['ohp-db', 'Seated Overhead Press (Dumbbell)', 'Shoulders', 'wr', 'Dumbbell'], ['ohp-stand-db', 'Standing Dumbbell Press', 'Shoulders', 'wr', 'Dumbbell'],
  ['ohp-machine', 'Shoulder Press (Machine)', 'Shoulders', 'wr', 'Machine'], ['arnold', 'Arnold Press', 'Shoulders', 'wr', 'Dumbbell'], ['landmine', 'Landmine Press', 'Shoulders', 'wr', 'Barbell'],
  ['push-press', 'Push Press', 'Shoulders', 'wr', 'Barbell'], ['lateral', 'Lateral Raise (Dumbbell)', 'Shoulders', 'wr', 'Dumbbell'], ['lateral-cable', 'Lateral Raise (Cable)', 'Shoulders', 'wr', 'Cable'],
  ['lateral-machine', 'Lateral Raise (Machine)', 'Shoulders', 'wr', 'Machine'], ['front-raise', 'Front Raise (Dumbbell)', 'Shoulders', 'wr', 'Dumbbell'], ['rear-delt', 'Reverse Fly (Machine)', 'Shoulders', 'wr', 'Machine'],
  ['rear-delt-db', 'Rear Delt Fly (Dumbbell)', 'Shoulders', 'wr', 'Dumbbell'], ['facepull', 'Face Pull', 'Shoulders', 'wr', 'Cable'], ['band-pull-apart', 'Band Pull-Apart', 'Shoulders', 'r', 'Band'],
  ['upright-row', 'Upright Row (Cable)', 'Shoulders', 'wr', 'Cable'], ['ext-rot', 'Cable External Rotation', 'Shoulders', 'wr', 'Cable'], ['ytw', 'Prone Y-T-W Raise', 'Shoulders', 'r', 'Dumbbell'],
  ['pike-pushup', 'Pike Push Up', 'Shoulders', 'r', 'Bodyweight'], ['handstand-hold', 'Wall Handstand Hold', 'Shoulders', 'd', 'Bodyweight'],
  // Arms
  ['curl-bb', 'Bicep Curl (Barbell)', 'Arms', 'wr', 'Barbell'], ['curl-db', 'Bicep Curl (Dumbbell)', 'Arms', 'wr', 'Dumbbell'], ['curl-ez', 'EZ Bar Curl', 'Arms', 'wr', 'Barbell'],
  ['hammer', 'Hammer Curl', 'Arms', 'wr', 'Dumbbell'], ['curl-incline', 'Incline Dumbbell Curl', 'Arms', 'wr', 'Dumbbell'], ['curl-preacher', 'Preacher Curl', 'Arms', 'wr', 'Machine'],
  ['curl-cable', 'Cable Curl', 'Arms', 'wr', 'Cable'], ['curl-conc', 'Concentration Curl', 'Arms', 'wr', 'Dumbbell'], ['curl-spider', 'Spider Curl', 'Arms', 'wr', 'Dumbbell'],
  ['curl-band', 'Band Curl', 'Arms', 'r', 'Band'], ['pushdown', 'Triceps Pushdown', 'Arms', 'wr', 'Cable'], ['pushdown-rope', 'Rope Pushdown', 'Arms', 'wr', 'Cable'],
  ['skull', 'Skullcrusher', 'Arms', 'wr', 'Barbell'], ['oh-tri', 'Overhead Triceps Extension (Cable)', 'Arms', 'wr', 'Cable'], ['oh-tri-db', 'Overhead Triceps Extension (Dumbbell)', 'Arms', 'wr', 'Dumbbell'],
  ['cgbp', 'Close-Grip Bench Press', 'Arms', 'wr', 'Barbell'], ['kickback', 'Triceps Kickback', 'Arms', 'wr', 'Dumbbell'], ['dip-bench', 'Bench Dip', 'Arms', 'r', 'Bodyweight'],
  ['diamond-pushup', 'Diamond Push Up', 'Arms', 'r', 'Bodyweight'], ['wrist-curl', 'Wrist Curl', 'Arms', 'wr', 'Dumbbell'], ['rev-curl', 'Reverse Curl', 'Arms', 'wr', 'Barbell'],
  ['dead-hang', 'Dead Hang', 'Arms', 'd', 'Bodyweight'],
  // Legs
  ['squat', 'Squat (Barbell)', 'Legs', 'wr', 'Barbell'], ['squat-pause', 'Pause Squat', 'Legs', 'wr', 'Barbell'], ['front-squat', 'Front Squat', 'Legs', 'wr', 'Barbell'],
  ['squat-box', 'Box Squat', 'Legs', 'wr', 'Barbell'], ['squat-sm', 'Squat (Smith Machine)', 'Legs', 'wr', 'Machine'], ['goblet', 'Goblet Squat', 'Legs', 'wr', 'Kettlebell'],
  ['leg-press', 'Leg Press', 'Legs', 'wr', 'Machine'], ['hack', 'Hack Squat', 'Legs', 'wr', 'Machine'], ['pendulum', 'Pendulum Squat', 'Legs', 'wr', 'Machine'],
  ['belt-squat', 'Belt Squat', 'Legs', 'wr', 'Machine'], ['rdl', 'Romanian Deadlift', 'Legs', 'wr', 'Barbell'], ['rdl-db', 'Romanian Deadlift (Dumbbell)', 'Legs', 'wr', 'Dumbbell'],
  ['sldl', 'Stiff-Leg Deadlift', 'Legs', 'wr', 'Barbell'], ['split-squat', 'Bulgarian Split Squat', 'Legs', 'wr', 'Dumbbell'], ['split-squat-bw', 'Split Squat (Bodyweight)', 'Legs', 'r', 'Bodyweight'],
  ['lunge', 'Walking Lunge', 'Legs', 'wr', 'Dumbbell'], ['lunge-rev', 'Reverse Lunge', 'Legs', 'wr', 'Dumbbell'], ['step-up', 'Step Up', 'Legs', 'wr', 'Dumbbell'],
  ['leg-curl', 'Leg Curl (Lying)', 'Legs', 'wr', 'Machine'], ['leg-curl-seat', 'Leg Curl (Seated)', 'Legs', 'wr', 'Machine'], ['nordic', 'Nordic Hamstring Curl', 'Legs', 'r', 'Bodyweight'],
  ['leg-ext', 'Leg Extension (Machine)', 'Legs', 'wr', 'Machine'], ['sissy', 'Sissy Squat', 'Legs', 'r', 'Bodyweight'], ['hip-thrust', 'Hip Thrust (Barbell)', 'Legs', 'wr', 'Barbell'],
  ['hip-thrust-m', 'Hip Thrust (Machine)', 'Legs', 'wr', 'Machine'], ['glute-bridge', 'Glute Bridge', 'Legs', 'r', 'Bodyweight'], ['cable-kickback', 'Cable Glute Kickback', 'Legs', 'wr', 'Cable'],
  ['abductor', 'Hip Abduction (Machine)', 'Legs', 'wr', 'Machine'], ['adductor', 'Hip Adduction (Machine)', 'Legs', 'wr', 'Machine'], ['calf', 'Standing Calf Raise', 'Legs', 'wr', 'Machine'],
  ['calf-seat', 'Seated Calf Raise', 'Legs', 'wr', 'Machine'], ['calf-sl', 'Single-Leg Calf Raise', 'Legs', 'r', 'Bodyweight'], ['tib-raise', 'Tibialis Raise', 'Legs', 'r', 'Bodyweight'],
  ['squat-bw', 'Air Squat', 'Legs', 'r', 'Bodyweight'], ['jump-squat', 'Jump Squat', 'Legs', 'r', 'Bodyweight'], ['wall-sit', 'Wall Sit', 'Legs', 'd', 'Bodyweight'],
  ['pistol', 'Pistol Squat', 'Legs', 'r', 'Bodyweight'], ['cossack', 'Cossack Squat', 'Legs', 'r', 'Bodyweight'],
  // Core
  ['plank', 'Plank', 'Core', 'd', 'Bodyweight'], ['side-plank', 'Side Plank', 'Core', 'd', 'Bodyweight'], ['hlr', 'Hanging Leg Raise', 'Core', 'r', 'Bodyweight'],
  ['hkr', 'Hanging Knee Raise', 'Core', 'r', 'Bodyweight'], ['cable-crunch', 'Cable Crunch', 'Core', 'wr', 'Cable'], ['ab-wheel', 'Ab Wheel', 'Core', 'r', 'Other'],
  ['dead-bug', 'Dead Bug', 'Core', 'r', 'Bodyweight'], ['bird-dog', 'Bird Dog', 'Core', 'r', 'Bodyweight'], ['pallof', 'Pallof Press', 'Core', 'wr', 'Cable'],
  ['russian-twist', 'Russian Twist', 'Core', 'r', 'Bodyweight'], ['crunch', 'Crunch', 'Core', 'r', 'Bodyweight'], ['sit-up', 'Sit Up', 'Core', 'r', 'Bodyweight'],
  ['decline-situp', 'Decline Sit Up', 'Core', 'r', 'Bodyweight'], ['v-up', 'V-Up', 'Core', 'r', 'Bodyweight'], ['hollow-hold', 'Hollow Body Hold', 'Core', 'd', 'Bodyweight'],
  ['mountain-climber', 'Mountain Climber', 'Core', 'd', 'Bodyweight'], ['woodchop', 'Cable Woodchop', 'Core', 'wr', 'Cable'], ['suitcase', 'Suitcase Carry', 'Core', 'dt', 'Dumbbell'],
  ['copenhagen', 'Copenhagen Plank', 'Core', 'd', 'Bodyweight'], ['squat-hold', 'Deep Squat Hold', 'Core', 'd', 'Bodyweight'],
  // Cardio
  ['run', 'Running', 'Cardio', 'dt', 'Other'], ['treadmill', 'Treadmill Run', 'Cardio', 'dt', 'Cardio machine'], ['incline-walk', 'Incline Treadmill Walk', 'Cardio', 'dt', 'Cardio machine'],
  ['walk', 'Walking', 'Cardio', 'dt', 'Other'], ['hike', 'Hiking', 'Cardio', 'dt', 'Other'], ['ruck', 'Ruck March', 'Cardio', 'dt', 'Other'],
  ['cycle', 'Cycling', 'Cardio', 'dt', 'Other'], ['bike-stat', 'Stationary Bike', 'Cardio', 'dt', 'Cardio machine'], ['bike-int', 'Bike Intervals', 'Cardio', 'd', 'Cardio machine'],
  ['assault-bike', 'Air Bike', 'Cardio', 'd', 'Cardio machine'], ['row-erg', 'Rowing (Machine)', 'Cardio', 'dt', 'Cardio machine'], ['ski-erg', 'Ski Erg', 'Cardio', 'dt', 'Cardio machine'],
  ['elliptical', 'Elliptical', 'Cardio', 'd', 'Cardio machine'], ['stairs', 'Stair Climber', 'Cardio', 'd', 'Cardio machine'], ['swim', 'Swimming', 'Cardio', 'dt', 'Other'],
  ['jump-rope', 'Jump Rope', 'Cardio', 'd', 'Other'], ['hiit', 'HIIT Circuit', 'Cardio', 'd', 'Other'], ['sprint', 'Sprints', 'Cardio', 'dt', 'Other'],
  ['burpee', 'Burpee', 'Full Body', 'r', 'Bodyweight'],
  // Full body / Olympic / strongman
  ['farmer', 'Farmer Carry', 'Full Body', 'dt', 'Dumbbell'], ['sled', 'Sled Push', 'Full Body', 'dt', 'Other'], ['sled-pull', 'Sled Pull', 'Full Body', 'dt', 'Other'],
  ['kb-swing', 'Kettlebell Swing', 'Full Body', 'wr', 'Kettlebell'], ['kb-tgu', 'Turkish Get-Up', 'Full Body', 'wr', 'Kettlebell'], ['kb-clean-press', 'Kettlebell Clean & Press', 'Full Body', 'wr', 'Kettlebell'],
  ['kb-snatch', 'Kettlebell Snatch', 'Full Body', 'wr', 'Kettlebell'], ['thruster', 'Thruster', 'Full Body', 'wr', 'Barbell'], ['wall-ball', 'Wall Ball', 'Full Body', 'r', 'Other'],
  ['box-jump', 'Box Jump', 'Full Body', 'r', 'Other'], ['battle-ropes', 'Battle Ropes', 'Full Body', 'd', 'Other'], ['bear-crawl', 'Bear Crawl', 'Full Body', 'dt', 'Bodyweight'],
  ['clean', 'Power Clean', 'Olympic', 'wr', 'Barbell'], ['hang-clean', 'Hang Clean', 'Olympic', 'wr', 'Barbell'], ['snatch', 'Power Snatch', 'Olympic', 'wr', 'Barbell'],
  ['clean-jerk', 'Clean and Jerk', 'Olympic', 'wr', 'Barbell'], ['trap-jump', 'Trap Bar Jump', 'Olympic', 'wr', 'Barbell'], ['med-ball-slam', 'Medicine Ball Slam', 'Full Body', 'r', 'Other'],
  ['mobility', 'Mobility Flow', 'Other', 'd', 'Other'], ['stretch', 'Stretching', 'Other', 'd', 'Other'], ['yoga', 'Yoga', 'Other', 'd', 'Other'], ['sport', 'Sport / Game', 'Other', 'd', 'Other']
];
const EX_LIB = EX_ROWS.map(([id, name, part, type, equip]) => ({ id, name, part, type, equip }));
const EQUIPS = ['Any', 'Barbell', 'Dumbbell', 'Machine', 'Cable', 'Bodyweight', 'Kettlebell', 'Band', 'Cardio machine', 'Other'];

// Mobility drills: [id, name, area, minutes, cue]
const MOB_ROWS = [
  ['cat-cow', 'Cat-Cow', 'Spine', 2, 'Slow, one breath per rep; move one vertebra at a time.'],
  ['thread-needle', 'Thread the Needle', 'Thoracic', 2, 'On all fours, reach under and rotate; 5 slow reps each side.'],
  ['open-book', 'Open Book', 'Thoracic', 2, 'Side-lying, knees stacked; rotate the top arm open and follow it with your eyes.'],
  ['tspine-ext', 'Foam Roller T-Spine Extension', 'Thoracic', 2, 'Roller under the upper back, hands behind head, extend over it in 3 spots.'],
  ['wall-angels', 'Wall Angels', 'Shoulders', 2, 'Back and arms against the wall; slide up and down without losing contact.'],
  ['shoulder-cars', 'Shoulder CARs', 'Shoulders', 2, 'Biggest slow circle the shoulder can make with the ribs locked down; 3 each way.'],
  ['band-dislocate', 'Band Pass-Throughs', 'Shoulders', 2, 'Wide grip on a band, pass it overhead and behind with straight arms.'],
  ['sleeper', 'Sleeper Stretch', 'Shoulders', 2, 'Side-lying on the shoulder, gently press the forearm down; 45 s each side.'],
  ['doorway-pec', 'Doorway Pec Stretch', 'Chest', 2, 'Forearm on a door frame, step through until you feel the chest; 45 s each side.'],
  ['lat-stretch', 'Lat Stretch (Bench)', 'Shoulders', 2, 'Elbows on a bench, sit the hips back and let the chest sink.'],
  ['dead-hang-m', 'Dead Hang', 'Shoulders', 1, 'Relaxed hang from a bar; let the shoulders open up.'],
  ['neck-cars', 'Neck CARs', 'Neck', 1, 'Slow half-circles, chin tucked; never force the end range.'],
  ['upper-trap', 'Upper Trap Stretch', 'Neck', 1, 'Ear to shoulder, gentle hand assist; 30 s each side.'],
  ['wrist-prep', 'Wrist Circles & Rocks', 'Wrists', 2, 'Circles both ways, then rock forward/back on all fours with palms flat.'],
  ['90-90', '90/90 Hip Switch', 'Hips', 3, 'Sit with both knees at 90°; rotate side to side, tall spine.'],
  ['pigeon', 'Pigeon Pose', 'Hips', 3, 'Front shin across the mat, square the hips; 60–90 s each side.'],
  ['couch', 'Couch Stretch', 'Hips', 3, 'Back knee against a wall/couch, squeeze the glute; 60–90 s each side.'],
  ['hip-flexor', 'Half-Kneeling Hip Flexor Stretch', 'Hips', 2, 'Tuck the pelvis, squeeze the back glute, shift forward; 45 s each side.'],
  ['frog', 'Frog Stretch', 'Hips', 2, 'Knees wide on all fours, rock the hips back slowly.'],
  ['hip-cars', 'Hip CARs', 'Hips', 2, 'On all fours or standing, draw the biggest slow circle with the knee; 3 each way.'],
  ['worlds-greatest', 'World’s Greatest Stretch', 'Full body', 3, 'Lunge, elbow to instep, rotate the arm to the sky; 5 each side.'],
  ['spiderman', 'Spiderman Lunge with Reach', 'Hips', 2, 'Deep lunge, hand inside the foot, reach up and rotate.'],
  ['butterfly', 'Butterfly Stretch', 'Hips', 2, 'Soles together, tall spine, gentle forward lean.'],
  ['adductor-rock', 'Adductor Rock-Backs', 'Hips', 2, 'One leg out to the side on all fours, rock back to feel the inner thigh.'],
  ['glute-stretch', 'Figure-4 Glute Stretch', 'Hips', 2, 'On your back, ankle over knee, pull the thigh in; 45 s each side.'],
  ['hamstring-floss', 'Hamstring Floss', 'Hamstrings', 2, 'Lying leg raise with a strap, bend and straighten the knee slowly.'],
  ['hamstring-stretch', 'Standing Hamstring Stretch', 'Hamstrings', 2, 'Heel on a low step, hinge at the hips with a flat back.'],
  ['jefferson', 'Jefferson Curl (light)', 'Hamstrings', 2, 'Very light weight, roll down one vertebra at a time and back up.'],
  ['pike-stretch', 'Seated Pike Stretch', 'Hamstrings', 2, 'Legs straight, hinge forward from the hips; breathe into it.'],
  ['quad-stretch', 'Standing Quad Stretch', 'Quads', 1, 'Heel to glute, knees together, tuck the pelvis; 30 s each side.'],
  ['ankle-rocks', 'Knee-to-Wall Ankle Rocks', 'Ankles', 2, 'Half-kneeling, drive the knee over the toes to the wall; 10 each side.'],
  ['calf-stretch', 'Calf Stretch (Wall)', 'Ankles', 2, 'Straight leg then bent leg against the wall; 30 s each version.'],
  ['deep-squat', 'Deep Squat Hold', 'Hips', 2, 'Sit in the bottom of a squat, elbows pushing knees out; hold a post if needed.'],
  ['squat-pry', 'Goblet Squat Pry', 'Hips', 2, 'Light kettlebell, sit deep and shift side to side.'],
  ['childs-pose', 'Child’s Pose', 'Spine', 2, 'Knees wide, arms long, breathe into the lower back.'],
  ['cobra', 'Cobra / Sphinx', 'Spine', 1, 'Gentle back extension on the forearms or hands; relax the glutes.'],
  ['supine-twist', 'Supine Twist', 'Spine', 2, 'Knees to one side, shoulders flat; 45 s each side.'],
  ['side-bend', 'Standing Side Bend', 'Spine', 1, 'Reach up and over, long through the side body.'],
  ['down-dog', 'Downward Dog', 'Full body', 1, 'Push the floor away, pedal the heels.'],
  ['inchworm', 'Inchworm', 'Full body', 2, 'Walk the hands out to a plank and back; 6–8 reps.'],
  ['leg-swings', 'Leg Swings', 'Hips', 1, 'Front-to-back and side-to-side, 10 each; hold a wall.'],
  ['arm-circles', 'Arm Circles', 'Shoulders', 1, 'Small to big, both directions.'],
  ['glute-bridge-m', 'Glute Bridge Hold', 'Hips', 1, 'Squeeze and hold at the top, ribs down.'],
  ['band-hip-dist', 'Banded Hip Distraction', 'Hips', 2, 'Band around the top of the thigh, lunge forward away from the anchor.'],
  ['scap-pushup', 'Scap Push-Ups', 'Shoulders', 1, 'Straight arms, let the chest sink then push the floor away.'],
  ['foam-quads', 'Foam Roll Quads & IT Band', 'Recovery', 3, 'Slow passes, pause on tender spots.'],
  ['foam-upper', 'Foam Roll Upper Back & Lats', 'Recovery', 3, 'Slow passes, arms crossed or overhead.'],
  ['foam-calves', 'Foam Roll Calves & Glutes', 'Recovery', 3, 'Slow passes, cross one leg over for more pressure.'],
  ['box-breath', 'Box Breathing', 'Recovery', 3, 'Inhale 4, hold 4, exhale 4, hold 4.'],
  ['legs-wall', 'Legs Up the Wall', 'Recovery', 3, 'Lie back with legs on the wall; slow nasal breathing.']
];
const MOB_LIB = MOB_ROWS.map(([id, name, area, min, cue]) => ({ id, name, area, min, cue }));
const MOB_AREAS = ['All', ...Array.from(new Set(MOB_ROWS.map(r => r[2])))];
const MOB_ROUTINES = [
  { id: 'morning', name: 'Morning Wake-Up', min: 10, note: 'Gentle full-body flow to start the day', drills: ['cat-cow', 'worlds-greatest', 'hip-cars', 'arm-circles', 'deep-squat'] },
  { id: 'hips', name: 'Hip Opener', min: 15, note: 'For tight hips from sitting or squatting', drills: ['90-90', 'couch', 'pigeon', 'frog', 'deep-squat'] },
  { id: 'shoulders', name: 'Shoulder Health', min: 12, note: 'Before pressing or for desk shoulders', drills: ['wall-angels', 'shoulder-cars', 'band-dislocate', 'doorway-pec', 'scap-pushup', 'dead-hang-m'] },
  { id: 'tspine', name: 'Thoracic & Posture', min: 10, note: 'Open the upper back and chest', drills: ['tspine-ext', 'thread-needle', 'open-book', 'doorway-pec', 'wall-angels'] },
  { id: 'pre-squat', name: 'Pre-Squat / Leg Day Prep', min: 8, note: 'Ankles, hips and adductors before squats', drills: ['ankle-rocks', 'leg-swings', 'adductor-rock', 'hip-flexor', 'squat-pry'] },
  { id: 'pre-press', name: 'Pre-Bench / Press Prep', min: 7, note: 'Shoulders, wrists and T-spine before pressing', drills: ['arm-circles', 'band-dislocate', 'thread-needle', 'scap-pushup', 'wrist-prep'] },
  { id: 'pre-pull', name: 'Pre-Pull / Deadlift Prep', min: 8, note: 'Hinge pattern and lats before pulling', drills: ['cat-cow', 'hamstring-floss', 'glute-bridge-m', 'lat-stretch', 'dead-hang-m'] },
  { id: 'post-run', name: 'Post-Run Recovery', min: 12, note: 'Calves, quads and hips after running or rucking', drills: ['calf-stretch', 'quad-stretch', 'hip-flexor', 'hamstring-stretch', 'glute-stretch', 'foam-calves'] },
  { id: 'hamstrings', name: 'Hamstring Flexibility', min: 12, note: 'Build towards touching your toes', drills: ['hamstring-floss', 'pike-stretch', 'jefferson', 'hamstring-stretch', 'down-dog'] },
  { id: 'desk', name: 'Desk Reset', min: 6, note: 'Quick break for long study or screen sessions', drills: ['neck-cars', 'upper-trap', 'doorway-pec', 'hip-flexor', 'side-bend'] },
  { id: 'ankles', name: 'Ankles & Knees', min: 8, note: 'Deeper squats and happier knees', drills: ['ankle-rocks', 'calf-stretch', 'quad-stretch', 'deep-squat'] },
  { id: 'full20', name: 'Full-Body Flow (20 min)', min: 20, note: 'Head-to-toe routine for rest days', drills: ['cat-cow', 'worlds-greatest', '90-90', 'couch', 'thread-needle', 'hamstring-floss', 'ankle-rocks', 'childs-pose'] },
  { id: 'foam', name: 'Foam Roll Recovery', min: 10, note: 'Roll out after hard sessions', drills: ['foam-quads', 'foam-calves', 'foam-upper', 'childs-pose'] },
  { id: 'bedtime', name: 'Bedtime Wind-Down', min: 10, note: 'Slow stretches and breathing before sleep', drills: ['childs-pose', 'supine-twist', 'glute-stretch', 'legs-wall', 'box-breath'] }
];
const routineItems = r => { const drills = r.drills.map(id => MOB_LIB.find(d => d.id === id)).filter(Boolean); return drills.map(d => ({ name: d.name, min: d.min, cue: d.cue })); };

// Preset workouts: exercises as [exId, sets, reps | {t} | {d,t}]
const PS = (id, n, r) => [id, Array.from({ length: n }, () => (typeof r === 'object' ? { ...r } : { w: null, r }))];
const PRESETS = [
  { id: 'p-fb-a', group: 'Beginner', name: 'Full Body A', note: '3×/week, alternate with B', ex: [PS('squat', 3, 8), PS('bench', 3, 8), PS('row-cable', 3, 10), PS('lateral', 2, 12), PS('plank', 3, { t: 45 })], mob: 'pre-squat' },
  { id: 'p-fb-b', group: 'Beginner', name: 'Full Body B', note: '3×/week, alternate with A', ex: [PS('rdl', 3, 8), PS('ohp-db', 3, 10), PS('pulldown', 3, 10), PS('goblet', 2, 12), PS('dead-bug', 3, 10)], mob: 'pre-pull' },
  { id: 'p-5x5-a', group: 'Strength', name: '5×5 · Workout A', note: 'Classic linear progression — add weight each session', ex: [PS('squat', 5, 5), PS('bench', 5, 5), PS('row-bb', 5, 5)], mob: 'pre-squat' },
  { id: 'p-5x5-b', group: 'Strength', name: '5×5 · Workout B', note: 'Classic linear progression — add weight each session', ex: [PS('squat', 5, 5), PS('ohp', 5, 5), PS('deadlift', 1, 5)], mob: 'pre-pull' },
  { id: 'p-push', group: 'Push / Pull / Legs', name: 'Push', note: 'Chest, shoulders, triceps', ex: [PS('bench', 4, 6), PS('ohp-db', 3, 10), PS('incline-db', 3, 10), PS('lateral', 3, 15), PS('pushdown-rope', 3, 12), PS('oh-tri', 2, 12)], mob: 'pre-press' },
  { id: 'p-pull', group: 'Push / Pull / Legs', name: 'Pull', note: 'Back, rear delts, biceps', ex: [PS('deadlift', 3, 5), PS('pullup', 3, 8), PS('row-cable', 3, 10), PS('facepull', 3, 15), PS('curl-incline', 3, 10), PS('hammer', 2, 12)], mob: 'pre-pull' },
  { id: 'p-legs', group: 'Push / Pull / Legs', name: 'Legs', note: 'Quads, hamstrings, glutes, calves', ex: [PS('squat', 4, 6), PS('rdl', 3, 8), PS('leg-press', 3, 12), PS('leg-curl-seat', 3, 12), PS('calf', 4, 12), PS('hlr', 3, 12)], mob: 'pre-squat' },
  { id: 'p-upper-a', group: 'Upper / Lower', name: 'Upper A (strength)', note: 'Heavier compounds', ex: [PS('bench', 4, 5), PS('row-bb', 4, 6), PS('ohp', 3, 6), PS('pullup-w', 3, 6), PS('curl-ez', 2, 10), PS('skull', 2, 10)], mob: 'pre-press' },
  { id: 'p-lower-a', group: 'Upper / Lower', name: 'Lower A (strength)', note: 'Heavier compounds', ex: [PS('squat', 4, 5), PS('rdl', 3, 6), PS('split-squat', 3, 8), PS('leg-curl', 3, 10), PS('calf', 3, 12)], mob: 'pre-squat' },
  { id: 'p-upper-b', group: 'Upper / Lower', name: 'Upper B (volume)', note: 'More reps, more angles', ex: [PS('incline-db', 3, 10), PS('pulldown', 3, 12), PS('chest-press', 3, 12), PS('row-chest', 3, 12), PS('lateral-cable', 3, 15), PS('rear-delt', 3, 15)], mob: 'shoulders' },
  { id: 'p-lower-b', group: 'Upper / Lower', name: 'Lower B (volume)', note: 'More reps, glute focus', ex: [PS('hack', 3, 10), PS('hip-thrust', 3, 10), PS('lunge', 3, 12), PS('leg-ext', 3, 15), PS('calf-seat', 3, 15), PS('cable-crunch', 3, 15)], mob: 'hips' },
  { id: 'p-arms', group: 'Specialty', name: 'Arms', note: 'Biceps + triceps supersets', ex: [PS('cgbp', 3, 8), PS('curl-bb', 3, 10), PS('pushdown-rope', 3, 12), PS('curl-incline', 3, 12), PS('oh-tri-db', 3, 12), PS('hammer', 3, 12)] },
  { id: 'p-glutes', group: 'Specialty', name: 'Glutes & Hamstrings', note: 'Posterior-chain day', ex: [PS('hip-thrust', 4, 8), PS('rdl', 3, 10), PS('split-squat', 3, 10), PS('leg-curl-seat', 3, 12), PS('abductor', 3, 15)], mob: 'hips' },
  { id: 'p-core', group: 'Specialty', name: 'Core Blast', note: '15 minutes, any day', ex: [PS('hlr', 3, 12), PS('pallof', 3, 12), PS('ab-wheel', 3, 10), PS('side-plank', 3, { t: 40 }), PS('hollow-hold', 3, { t: 30 })] },
  { id: 'p-db', group: 'Home & travel', name: 'Dumbbell-Only Full Body', note: 'Just a pair of dumbbells', ex: [PS('goblet', 3, 12), PS('bench-db', 3, 10), PS('row-db', 3, 10), PS('rdl-db', 3, 10), PS('ohp-stand-db', 3, 10), PS('curl-db', 2, 12)] },
  { id: 'p-bw', group: 'Home & travel', name: 'Bodyweight Anywhere', note: 'No equipment, hotel-room friendly', ex: [PS('pushup', 4, 15), PS('squat-bw', 4, 20), PS('split-squat-bw', 3, 12), PS('pike-pushup', 3, 10), PS('glute-bridge', 3, 15), PS('plank', 3, { t: 60 })] },
  { id: 'p-kb', group: 'Home & travel', name: 'Kettlebell Circuit', note: 'One bell, big effort', ex: [PS('kb-swing', 5, 15), PS('goblet', 4, 10), PS('kb-clean-press', 4, 6), PS('kb-tgu', 3, 2), PS('suitcase', 3, { d: 0.04 })] },
  { id: 'p-z2', group: 'Conditioning', name: 'Zone 2 Cardio', note: 'Easy pace you could talk at', ex: [PS('incline-walk', 1, { d: 3, t: 2400 })], mob: 'post-run' },
  { id: 'p-hiit', group: 'Conditioning', name: 'Intervals', note: 'Short, hard, done', ex: [PS('assault-bike', 8, { t: 30 }), PS('row-erg', 4, { d: 0.25, t: 60 }), PS('burpee', 3, 10)] },
  { id: 'p-hybrid', group: 'Conditioning', name: 'Hybrid Strength + Engine', note: 'Lift, then a finisher', ex: [PS('trap-jump', 4, 3), PS('thruster', 3, 8), PS('pullup', 3, 8), PS('sled', 4, { d: 0.02 }), PS('farmer', 3, { d: 0.04 })] }
];
